dist: xenial
language: python
cache: pip

python:
  - "3.9"
  - "3.11"

env:
  matrix:
    - DJANGO=3.2
    - DJANGO=4.2

matrix:
  fast_finish: true
  include:
    - { python: "3.11", env: TOXENV=isort }
    - { python: "3.11", env: TOXENV=black }
    # - { python: "3.11", env: TOXENV=docs }

install:
  - pip install tox tox-travis

script:
  - tox

after_success:
  - pip install codecov
  - codecov -e TOXENV,DJANGO

notifications:
  email: false
