dist: xenial
language: python
cache: pip

python:
  - "3.11"
  - "3.12"
  - "3.13"

env:
  matrix:
    - DJANGO=4.2
    - DJANGO=5.2

matrix:
  fast_finish: true
  include:
    - { python: "3.11", env: TOXENV=isort }
    - { python: "3.11", env: TOXENV=black }
    - { python: "3.12", env: TOXENV=isort }
    - { python: "3.12", env: TOXENV=black }
    - { python: "3.13", env: TOXENV=isort }
    - { python: "3.13", env: TOXENV=black }

install:
  - pip install tox tox-travis

script:
  - tox

after_success:
  - pip install codecov
  - codecov -e TOXENV,DJANGO

notifications:
  email: false
