dist: xenial
language: python
cache: pip

python:
  - "3.6"
  - "3.7"

env:
  matrix:
    - DJANGO=2.0
    - DJANGO=2.1
    - DJANGO=2.2

matrix:
  fast_finish: true
  include:
    - { python: "3.7", env: TOXENV=isort }
    - { python: "3.7", env: TOXENV=black }
    # - { python: "3.7", env: TOXENV=docs }

install:
  - pip install tox tox-travis

script:
  - tox

after_success:
  - pip install codecov
  - codecov -e TOXENV,DJANGO

notifications:
  email: false
