[tool.black]
line-length = 120

[tool.isort]
profile = "black"
known_first_party = "djangorestframework-inclusions"
combine_as_imports = true
include_trailing_comma = true
line_length = 120
multi_line_output = 3
skip = ["env", ".tox" , ".history", ".eggs"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
split_on_trailing_comma = true
